[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "at-spi2-atk", "xorg.libX11", "xorg.libxcb", "glib", "gtk3", "cairo", "pango", "cups", "libxkbcommon", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXfixes", "xorg.libXrandr", "mesa"]

[phases.install]
cmds = ["npm ci"]
cacheDirectories = ["/root/.npm"]
